# Generated by Django 4.2 on 2026-03-30 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='disability',
            field=models.CharField(blank=True, choices=[('deaf', 'Deaf'), ('blind', 'Blind'), ('dumb', 'Dumb (Speech Impaired)'), ('cognitive', 'Cognitive')], max_length=20, null=True),
        ),
    ]
